### ISSUE TITLE
If the function called in map does not return anything, it will convert to a nothing, and call followup or elses

### ISSUE THREAD

**Issue by cbefus** [cbefus/optional.py#20]
reference https://github.com/cbefus/optional.py/blob/master/optional/something.py#L30

if we map an example function that returns nothing (None) then we will create a nothing from something and any attached `or_else` etc. will be called.

Example:
```
def do_stuff(stuff):
    print(stuff)

Optional.of("Hello").map(do_stuff).or_else_raise(Exception("BOOM"))
``` 

This will print "Hello" but will also raise the "BOOM" exception!

**Comment by dpassen** [comment]
This is hard to solve without a type system.

**Comment by dpassen** [comment]
I think we have to assume this is working as designed. You should be using `if_present` with the do_stuff method.

**Comment by cbefus** [comment]
Yes.  non-issue - my bad.
