### ISSUE TITLE
An or function which returns the first non empty optional

### ISSUE THREAD

**Issue by cbefus** [cbefus/optional.py#28]
something like:
```python
return Optional.empty() \
     .or(Optional.empty()) \
     .or(Optional.of(3)) \
     .or(Optional.of(4))
```
would return Optional.of(3) where as:
```python
return Optional.empty() \
     .or(Optional.empty()) \
     .or(Optional.empty())
```
would return Optional.empty()

It would also be nice if we could pass suppliers, such that we only execute a supplier if the result of the previous suppliers was empty.

**Comment by dpassen** [comment]
For documentation's sake, the solution here is Python's built-in `or`.

The first example can be done as follows:
```py
return Optional.empty() or \
       Optional.empty() or \
       Optional.of(3) or \
       Optional.of(4)
```

and the second:
```py
return Optional.empty() or \
       Optional.empty() or \
       Optional.empty()
```
